name: Trigger Deploy

on:
  workflow_dispatch:
    inputs:
      buildCode:
        description: "Build Code"
        required: true
        type: string
      targetEnvironment:
        description: "Target Environment"
        required: true
        type: choice
        options:
          - d1
          - d2
          - s1
          - d3
          - d4
          - d5
          - p1
          - d6
          - d7

jobs:
  call-reusable-deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      buildCode: ${{ github.event.inputs.buildCode }}
      targetEnvironment: ${{ github.event.inputs.targetEnvironment }}
